#just run plan as i deployed it locally, we could setup a terraform backend in cloud storage
name: Terraform Plan 

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  PROJECT_NUMBER: ${{ secrets.GKE_PROJECT_NUMBER }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GAR_LOCATION: asia-northeast1 
  GKE_CLUSTER: online-boutique 
  GKE_ZONE: asia-northeast1  

jobs:
  setup-build-publish-deploy:
    name: Terraform init, plan
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: "projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github/providers/github"
        service_account: ${{env.GCP_SERVICE_ACCOUNT}}
        project_id: ${{env.PROJECT_ID}}


    - uses: hashicorp/setup-terraform@v3

    - name: "tf init"
      run: |-
        cd terraform/
        terraform init      

    - name: 'tf-plan'
      run: |- 
        cd terraform/
        terraform plan -no-color